name: Android Build & Release

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      # Dependency extraction tasks (extractOrtAar, extractOpenCvAar) will run automatically
      run: ./gradlew assembleDebug --stacktrace --no-daemon

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: beautyapp-apks
        path: app/build/outputs/apk/debug/*.apk

    - name: Extract Commit Info
      id: commit_info
      run: |
        echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
        echo "author=$(git log -1 --pretty=%an)" >> $GITHUB_OUTPUT
        echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Update Dev Release
      uses: ncipollo/release-action@v1
      with:
        tag: "dev"
        allowUpdates: true
        name: "Experimental CV Lab - Dev Build"
        body: |
          ### ðŸ›  Build Details
          - **Message:** ${{ steps.commit_info.outputs.msg }}
          - **Commit:** `${{ steps.commit_info.outputs.sha }}`
          - **By:** @${{ steps.commit_info.outputs.author }}
          - **Time:** ${{ github.event.head_commit.timestamp }}
          
          *This is an automated build for ECVL.*
        artifacts: "app/build/outputs/apk/debug/*.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
        replacesArtifacts: true